ToDoApp/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToDoApp.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false)]
        public string Description { get; set; }
        public bool IsDone { get; set; }
        public virtual ApplicationUser User { get; set; }

    }
}

ToDoApp/Controllers/ToDoesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class ToDoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToDoes
        public ActionResult Index()
        {
            return View();
        }

        private ApplicationUser GetCurrentUser()
        {
            // get id of current user
            string currentUserId = User.Identity.GetUserId();
            // use lambda expression to get the user by currentuserId
            return db.Users.FirstOrDefault(user => user.Id == currentUserId);
        }

        private IEnumerable<ToDo> GetMyToDoes()
        {

            IEnumerable<ToDo> myTodoes = db.ToDos.ToList().Where(todo => todo.User == GetCurrentUser());

            int completedTodoCount = 0;
            foreach (ToDo todo in myTodoes)
            {
                if (todo.IsDone)
                {
                    completedTodoCount++;
                }
            }

            // get percentage complete
            double completePercent = Math.Round(100f * ((float)completedTodoCount / (float)myTodoes.Count()));
            
            // if is NaN (can be when user has no items) show 0 instead of NaN
            ViewBag.Percent = Double.IsNaN(completePercent) ? 0 : completePercent;

            // get only the current users list of todo items
            return myTodoes;
        }

        public ActionResult BuildToDoTable()
        {
            // only return todo's for the user
            return PartialView("_ToDoTable", GetMyToDoes());
        }

        // GET: ToDoes/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Description")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                // get id of current user
                string currentUserId = User.Identity.GetUserId();
                // use lambda expression to get the user by currentuserId
                ApplicationUser currentUser = db.Users.FirstOrDefault(user => user.Id == currentUserId);
                // add the user to the ToDo item to create the link with Foreign Key
                toDo.User = currentUser;
                toDo.IsDone = false; // always going to be false when creating a todo item
                ModelState.Clear();
                db.ToDos.Add(toDo);
                db.SaveChanges();
            }

            // after creating we want only the table to update, showing new todo item
            return PartialView("_ToDoTable", GetMyToDoes());
        }

        // POST: ToDoes/Edit/5
        public ActionResult AJAXEdit(int? id, bool isDone)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            } else
            {
                toDo.IsDone = isDone;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
            }
            // after editing we want only the table to update, showing todo item
            return PartialView("_ToDoTable", GetMyToDoes());
        }


        public ActionResult AJAXEditDescription(int? id, string description)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.Description = description;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
            }
            // after editing we want only the table to update, showing todo item
            return PartialView("_ToDoTable", GetMyToDoes());
        }


        public ActionResult AJAXDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            } else
            {
                db.ToDos.Remove(toDo);
                db.SaveChanges();
            }
            return PartialView("_ToDoTable", GetMyToDoes());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoApp/Views/ToDoes/Index.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Todoes";
}

<h4 class="col m12">My ToDo List</h4>


<div id="tableDiv" class="col m12"></div>
<div id="todoCreateForm" class="col m12">
    <!-- Send request using ajax and onSuccess clear submitted item and remove focus and update table to reflect changes -->
    @using (Ajax.BeginForm("AJAXCreate", "ToDoes", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv",
        OnSuccess = "$('#Description').val(''); $('#Description').blur(); $('#Description').removeClass('valid');"
    }))
    {

    <div class="form-group">
        @Html.AntiForgeryToken()
        <div id="todo-input" class="col-md-10">
            @Html.EditorFor(model => model.Description, new {  htmlAttributes = new { placeholder = "Add new item...",  @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    }
</div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Custom_Scripts/BuildTable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    }

ToDoApp/Views/ToDoes/_ToDoTable.cshtml
@model IEnumerable<ToDoApp.Models.ToDo>

<div class="valign-wrapper">
    <div id="progress-percent">@(ViewBag.Percent)%</div>
    <div class="progress">
        @if (ViewBag.Percent == 100)
        {
            <div id="progress-complete" class="determinate" style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
        }
        else
        {
            <div class="determinate" style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
        }

    </div>
</div>

<table class="table">
    @if (Model.Count() == 0)
    {
        <p>No ToDo items have been created! To add a ToDo item fill in the field below and then press enter.</p>
    }
    else
    {
    foreach (var item in Model)
    {
        <tr>
            <td class="checkbox-cell">
                <label>
                    <input id="@(item.Id)" type="checkbox" class="filled-in" @(item.IsDone ? "checked='checked'" : "") />
                    <span></span>
                </label>
            </td>
            <td>
                @if (item.IsDone)
                {
                    <div class="todo-complete">@Html.DisplayFor(modelItem => item.Description)</div>
                }
                else
                {
                    <div class="form-group">
                        @Html.AntiForgeryToken()
                        <div>
                            @Html.EditorFor(modelItem => item.Description, new { htmlAttributes = new { id = item.Id, Value = item.Description, @class = "form-control todo-input-item" } })
                            @Html.ValidationMessageFor(modelItem => item.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                }
            </td>

            <td>
                <a class="delete-button btn-floating btn-small waves-effect waves-light" id="@(item.Id)" href="/"><i class="material-icons">delete</i></a>
            </td>
        </tr>
    }
    }

</table>

<script src="~/Custom_Scripts/CheckBoxListener.js"></script>
<script src="~/Custom_Scripts/DescriptionEnterListener.js"></script>
<script src="~/Custom_Scripts/ItemDeleteListener.js"></script>